string a = "hello ";
string b = "world!";
Console.Write("введите число: ");
double x = Convert.ToDouble(Console.ReadLine());
Console.Write("введите фамилию: ");
string sur = Console.ReadLine();
Console.Write("введите имя: ");
string name = Console.ReadLine();
Console.Write("введите отчество: ");
string ogl = Console.ReadLine();
double c = x + x;
double v = x - x;
double n = x * x;
double m = x / x;
double p1health = 50;
double p1damage = 75;
double p1def = 25;
double m1health = 100;
double m1damage = 50;
double m1def = 5;
double m2power = m1damage / p1def;
double p2power = p1damage / m1def;
double p2health = p1health - m2power;
double m2health = m1health - p2power;
Console.WriteLine($"{a + b}  sum:{c}  raz:{v}  ymn:{n}  otn:{m}");
Console.WriteLine($"фамилия:{sur}  имя:{name}  отчество:{ogl}");
Console.WriteLine($"МОНСТР: урон:{m1damage} здоровье:{m1health} деф:{m1def}");
Console.WriteLine($"ЧЕЛОВЕК: урон:{p1damage} здоровье:{p1health} деф:{p1def}");
Console.WriteLine($"Итоги схватки:");
Console.WriteLine($"МОНСТР: здоровья осталось:{m2health}");
Console.WriteLine($"ЧЕЛОВЕК: здоровья осталось:{p2health}");